### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by winterheart** [punesemu/puNES#108]
Hello.

Seems there lots of updates since last release 0.105, including fixing GCC 10 and Qt 5.15 compilation. Maybe it's time for new tag?

**Comment by punesemu** [comment]
Hi witnerheart
I was going to release a new release after adding support to the HD Packs, but I didn't have time to work on it so I think the time has come to release it (also because I would like to see the bugs [710612](https://bugs.gentoo.org/710612) resolved in this list [705764](https://bugs.gentoo.org/705764)) :grin:

**Comment by punesemu** [comment]
[Released](https://github.com/punesemu/puNES/releases/tag/v0.106).

**Comment by winterheart** [comment]
Thank you, https://github.com/gentoo/gentoo/pull/16876 on the way.
