### ISSUE TITLE
About intergrating a translation to the emulator

### ISSUE THREAD

**Issue by owomomo** [punesemu/puNES#125]
Hello.
I saw a [post](https://www.ppxclub.com/forum.php?mod=viewthread&tid=702882) that the author of puNES wants to intergrate my translation to the emulator.
I'm pleased to do it, reply to me to let me know what should I prepare if you saw this post.

**Comment by punesemu** [comment]
Hi owomomo, first of all, thank you for the support for the emulator and yes I wrote you on that forum. As I told you I'd like to integrate your translation. I need the TS file with your translation. I'll put it in the src/gui/designer/translations directory and add your translation to the ones on https://crowdin.com/project/punes. Which of those displayed in the image should I add?
![Chinese](https://user-images.githubusercontent.com/14859058/103436359-dfa62380-4c1a-11eb-91bd-b5a1295c99a2.png)
Once added on crowdin you can always update or edit the translation through a convenient editor integrated into the platform, you just have to sign up (since you already have a github account and you can connect using that, it's really simple).

**Comment by owomomo** [comment]
You can add Chinese Simplified.

**Comment by punesemu** [comment]
Done.

**Comment by owomomo** [comment]
Here's the translated .ts file, it can be attached to the project.
[zh_CN.zip](https://github.com/punesemu/puNES/files/5758884/zh_CN.zip)

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/85ab5f0b4322e9f22d93d42aa78ba6245414c940
