### ISSUE TITLE
Reduce sprite flickering by buffering frames

### ISSUE THREAD

**Issue by tbertels** [punesemu/puNES#25]
I'm wondering if it would be possible to:
1. buffer three frames (adding an input lag of 50/100 ms)
2. if a sprite gets hidden for a frame of two then reappears, consider it as sprite flickering
3. show the sprite that would be otherwise hidden during both frames, using an average for its position

Limitation: doesn't take into account the sprite animation

**Comment by punesemu** [comment]
If you don't want to see the sprites flickering you can use the "Unlimited sprites" option in Setting/PPU menu.

**Comment by tbertels** [comment]
It's already enabled, but it doesn't prevent (all) flickering on Nintendo World Cup.

**Comment by punesemu** [comment]
If there are flicker despite the option, it means that the sprites that disappear are not part of the [PPU OAM](http://wiki.nesdev.com/w/index.php/PPU_OAM) (the game for some reason has not inserted) then the emulator could never draw them to video because not exist for him.

**Comment by tbertels** [comment]
Yes, I think the game manages the sprites limit itself.
That's why I suggested to remember them in a buffer.
Of course, if it's the only game with this problem, it's less useful.

**Comment by jcdenton2k** [comment]
One thing to keep in mind, certain games DEPEND on there to be a sprite limit in order to hide things or do other tricks.

Legend of Zelda 1 NES = going under a dungeon overhang, Link will appear if no sprite limit

Ninja Gaiden = Enemies/bullets will spawn far more often making the game HARDER if no sprite limit

Rygar = Slowdown with tons of action on screen will NOT happen if no sprite limit; makes it harder

CV2: Simon's Quest = Simon will have legs visible in the Neon-purple/pink swamp if you have no sprite limit; you should enable it so the legs are hidden as they were intended.

Just keep this in mind before you play all games with no sprite limit.
