### ISSUE TITLE
cyrillic symbols in path (tested on Win10)

### ISSUE THREAD

**Issue by eugene-s-nesdev** [punesemu/puNES#31]
Hi, Fabio. It's test on new machine with Win10 on the work.

For example: if you set punes to: C:\emulation\кириллица\punes\punes64_p.exe
it will create C:\emulation\êèðèëëèöà\punes as workfolder.

If you have non-portable version, and have cyrillic name in default windows path,
punes won't open workfolder, and won't save config
http://savepic.ru/12151710.png
(it's not "IE" it must be "ПК" in path on screenshot)

**Comment by punesemu** [comment]
Fixed in https://github.com/punesemu/puNES/commit/777a6ef97fdd036b5cd950e38ebfc8248ac7d09f.

Last 0.101 WIP
Windows:
https://dl.dropboxusercontent.com/u/21595068/punes32.wip.d3d9.zip
https://dl.dropboxusercontent.com/u/21595068/punes64.wip.d3d9.zip
https://dl.dropboxusercontent.com/u/21595068/punes32.wip.sdl.zip
https://dl.dropboxusercontent.com/u/21595068/punes64.wip.sdl.zip
Linux:
https://dl.dropboxusercontent.com/u/21595068/punes32
https://dl.dropboxusercontent.com/u/21595068/punes64

Given the amount of changed codes, it's likely that there is some new bugs. I tried to verify everything, but something might have missed.
