### ISSUE TITLE
Feature Request: 4:3 Display Aspect Ratio

### ISSUE THREAD

**Issue by possiblyneal** [punesemu/puNES#316]
There should be a 4:3 aspect ratio option. This is what all consumer TVs were during the active life of the NES. There was no practical way to see the output of an NES other than 4:3. This is also what developers would have been testing their games on.

**Comment by vaguerant** [comment]
The TVs themselves were 4:3, but that doesn't mean the resulting image was. There's a misconception that analogue TVs somehow just naturally resized all images to exactly fit the 4:3 aspect ratio, but that is completely untrue. TVs back then, as they do now, display what you tell them to display.

## Background, what's overscan?
Let's stick to the vertical first, because it's simpler. The NES tells the TV to display 240 scanlines. That's technically not compliant with the television standard but it's fine, don't think about it. The TV does its best to display those 240 lines, but "its best" will mean different things on different TVs. Here's an example shot of Super Mario Bros. showing the entire visible area:
<div align="center">

![WUP-FAAJ_000002](https://github.com/punesemu/puNES/assets/5259025/5566d828-0080-4f37-9a4a-3b6eed90f4db)
</div>

On a period TV, you might see a bit less sky and a lot less ground than that and a lot of emulators will "fake" this behavior by doing something like this:

<div align="center">

![image](https://github.com/punesemu/puNES/assets/5259025/3f401b87-d012-490e-893a-ba6e111e24f2)
</div>
Ignore the sides for now and just focus on the fact that a bit of the picture has been cut off at the top and bottom. This is simulating what's called overscan--sorry if I'm explaining in too much detail, it'll help later. If your TV is not perfectly tuned to fit exactly 240 lines into the part of the TV that's ... made of glass and you can see picture on, the rest will get cut off. This is normal behavior. The calibration can also drift over time, so a TV fresh from the factory might show a bit more than an older TV, etc.

Now, everybody involved knew about this. Nintendo knew about it, third-party developers knew, so basically every game was designed around the knowledge that the stuff around the edges might not make it onto the TV screen and be visible to the player. Look at the very first screenshot again and observe how much space there is on the top **and** the left between the score counter's `MARIO` and the edges of the picture. This is a good indication of how much Nintendo expects might get cut off on little Jimmy's family TV. It's not that *every* TV will cut that much, but that's an amount that Nintendo has decided is common enough for them to cater to it.

Here's another screenshot, this time from Castlevania. It's a good test case because it's simultaneously good **and** bad at preparing for overscan.

<div align="center">

![Castlevania (USA) (Rev 1)_000001](https://github.com/punesemu/puNES/assets/5259025/766686fc-7b89-4c04-92b2-fa508548bbf9)
</div>

Observe that Konami has left the top and bottom of the screen **completely blank**, it's just empty black space. Since a lot of TVs wouldn't have shown those parts of the picture anyway, nobody is missing out on much. Where Mario just makes the top/bottom "boring stuff" (extra sky and ground tiles), Castlevania fills it with nothing. Either way works, you can lose some picture from the top/bottom and it's fine for gameplay purposes.

At the same time though, Konami has rammed their text (`SCORE`, `PLAYER`, `ENEMY`) right up against the left edge of the picture. This is pretty bad, and little Jimmy is going to wonder what `CORE`, `LAYER` and `NEMY` mean when he sees this:

<div align="center">

![9ss90026ccg11](https://github.com/punesemu/puNES/assets/5259025/97acb4a3-61e7-42ca-a75e-7b6b3f9d0029)
</div>

(Image stolen from [this Reddit thread](https://old.reddit.com/r/crtgaming/comments/97n4a6/can_anyone_help_with_this_hsiz_issue_on_sony/))

## Get on with it, how is overscan relevant?
Not only did developers (except Konami) know about overscan, so did the people in charge of designing the NES hardware. And so, separately from the **number of pixels** (256), they had to decide: "How much of the maximum screen width should we stretch these 256 pixels across?" The obvious first answer might be, "All of it, fill the whole thing up so we've got a nice big picture." 

But then the second answer is "**Somewhat less than all of it**, because I read an extremely long GitHub comment which explained that overscan is going to cut off the edges anyway. Why waste our precious few pixels on parts of the screen nobody is going to see?"

Then somebody would ask "What the hell is GitHub?"

Nintendo's hardware people decided they would fill up **about 91% of a true 4:3 image horizontally** and leave the rest empty. This would mean more of the image gets seen, and even games like Castlevania up there which do a **terrible** job of accounting for overscan are still *fairly* playable, because Nintendo already baked in that 9% leeway. If the NES wasn't already compensating for overscan, whoever that Castlevania guy is (I admit it, I've never played one. Is it Andy Richter?) wouldn't even be *visible on the TV* in that photo above.

All of this is only working out because the NES **isn't** displaying a 4:3 picture. The console itself is deliberately leaving parts of that 4:3 ratio blank.

## Well then what's the NES's real aspect ratio?

Oh, by the way, I'm not getting into PAL here, PAL is its own problem. This whole thing is talking NTSC.

If you want to think in terms of 4:3 specifically, then counting all 240 lines and the 91% width, the NES aspect ratio is roughly 3.66:3. Now, I can hear the objections already: there's no way the NES is 3.66:3, it filled up my whole 4:3 TV back in the day! Hold up a second, remember the first thing we talked about, *vertical* overscan. Just like you can't see the empty part on the sides that falls off the edges of your screen, you can't see the "boring" parts on the top and bottom that fall off your TV either, and this is how we claw our way back to 4:3.

Here is puNES displaying in its 8:7 PAR mode.

<div align="center">

![WUP-FAAJ_000001](https://github.com/punesemu/puNES/assets/5259025/cb507101-981c-4f7e-afa1-de6b2158a22b)

</div>

And here it is with some black bars added so you can see the entire 4:3 area (with ~9% left blank):

<div align="center">

![image](https://github.com/punesemu/puNES/assets/5259025/11767b9a-eb11-41a6-bdb4-8f4c76970d1f)
</div>

This is the correct NES aspect ratio of ~3.66:3, but I know it's immediately objectionable. You're **absolutely right**, this is not what Super Mario Bros. looked like on a TV from 1981. Back then, the aspect ratio looked more like this:

<div align="center">

![image](https://github.com/punesemu/puNES/assets/5259025/a18ed9bf-0bf3-421d-8c26-72f66b567f7b)

</div>

Yes! There! Exactly 4:3, the way it was always intended!

But the thing is, that image is the same as the one right above it. Here's an animated GIF which toggles between 3.66:3 and 4:3:

<div align="center">

![WUP-FAAJ_000001](https://github.com/punesemu/puNES/assets/5259025/aa8521fd-c95b-4892-b8aa-d285dfe2c579)
</div>

The picture in the video signal coming out of the NES *is* ~3.66:3, but the NES was giving your TV **more than enough picture** to fill 4:3, so when your TV inevitably lost the **empty** sides and the **boring** top and bottom to overscan, the result was a picture that filled up your 4:3 TV, not because the picture was exactly 4:3, but because your TV was.

## And?
About the closest you can get to "perfect" 4:3 from a NES is to set up the video config (in puNES or other emulators) like so:
* **Overscan**
  * Up: 10
  * Down: 10
  * Left: 0
  * Right: 0
* **Pixel Aspect Ratio**
  * 8:7 (NTSC TV)

Trying to to "force" the image into 4:3 by stretching 256\*240 is not accurate to the real hardware and not what the developers were working with. The aspect ratio you're getting in puNES when you have the 8:7 (NTSC TV) setting enabled is correct and it *is* what the developers were working with.

Perhaps the best example to show this is Kirby's Adventure. It starts up with a little animation teaching you how to draw Kirby.

<div align="center">

![image](https://github.com/punesemu/puNES/assets/5259025/4dc3f511-4890-4d82-ac70-4ba4ce5ba274)
Uncorrected 1:1 PAR
<hr>

![image](https://github.com/punesemu/puNES/assets/5259025/a05ebec0-e4a6-4826-96ed-503f8e8b44a5)
Corrected ~3.66:3 aspect ratio
<hr>

![image](https://github.com/punesemu/puNES/assets/5259025/d2bae3c3-c7b7-4ee1-83bd-059182c857f0)
Forced 4:3 aspect ratio

</div>
<hr>

Which one looks like a circle?

**Comment by punesemu** [comment]
Hi @vaguerant, many thanks for your very detailed explanation. I consider this issue closed.

**Comment by possiblyneal** [comment]
@vaguerant may be getting caught up on the differences between Pixel Aspect Ratio (PAR) and Display Aspect Ratio (DAR). PAR is the width/height ratio of the source image in pixels, whereas DAR is the width/height ratio of the display. Aspect ratio is not preserved when the NES converts its digital signals to the analog signals that a CRT TV uses. The CRT TV stretches any input signal it receives to fill the screen after cropping an amount of overscan, which users could adjust, but were typically left at factory defaults.

An 8:7, 3.66:3, or any other PAR source, when cropped and stretched to fill up a 4:3 display, will always result in a 4:3 picture.

@vaguerant even acknowledges this in their post here:

> but the NES was giving your TV more than enough picture to fill 4:3, so when your TV inevitably lost the empty sides and the boring top and bottom to overscan, the result was a picture that filled up your 4:3 TV, not because the picture was exactly 4:3, but because your TV was.

A picture that fills up a 4:3 TV will, by definition, be a 4:3 picture.

 There are many incorrect statements made in the post above. I'm not going to address them all. I'll discuss only the "smoking gun" -- Kirby's Adventure.

While the screenshots of Kirby's Adventure create a compelling argument, I'm going to show you the screenshot that @vaguerant didn't show you. Here is Kirby's Adventure running in Mesen at a 4:3 aspect ratio with the following overscan: top: 12, bottom: 8, left and right: 0 (based on Magnavox MS2530 C225). This cannot be replicated in puNES because it does not handle overscan correctly.

![kirby3](https://github.com/punesemu/puNES/assets/130699270/8ba18075-585d-4955-ba89-b14c479a1b60)

Not only does this screenshot show Kirby being drawn with a circle, but most importantly, it's also in an aspect ratio that matches the display aspect ratio of the TVs That were manufactured at the time of the NES' release. @vaguerant's 3.66:3 screenshot, if placed directly on a 4:3 display would have black bars on the left and right of the screen. No one played games like that. The TV screens were already small enough at the time.

Before someone claims that this is not correct because Kirby is not drawn as a perfect circle, I know. But the intro doesn't say to draw a perfect circle, and while you can adjust overscan to make Kirby a perfect circle in the title screen, he will not be a perfect circle in game. Game artists at this time had the very difficult job of creating game art with square pixels on a desktop in anticipation that they would be stretched to rectangular pixels to fit a TV screen, then stretched an additional unknown amount due to overscan differing between TV models. You can find examples all over the internet with people claiming that so and so aspect ratio is the correct aspect ratio because the moon in a particular game looks more circular. In reality, the only thing that this proves is that the tools at the time were imperfect and the technology was far from perfect. People (artists) aren't perfect either.

While there is no right or wrong way to enjoy playing old Nintendo games, this is the aspect ratio that most faithfully recreates how the picture was originally displayed. @punesemu I'm not asking that this be the only aspect ratio offered by puNES, but just an option for those of us looking for a more faithful recreation of the system. Would you please reopen this issue?

If anyone has any further doubt that 4:3 is not the correct aspect ratio, please download GIMP or Photoshop and create a 4:3 box (400x300 pixels will work), this will represent the TV screen. Then in a new layer, create an image in the aspect ratio of your choice and try to fill the 4:3 box completely while keeping the aspect ratio of your image intact. You will always be left with empty bars on two sides of the “screen” with no picture. Finally, watch a YouTube video of someone playing an NES on a CRT TV to see that the picture filled the entire screen.

**Comment by vaguerant** [comment]
> PAR is the width/height ratio of the source image in pixels

With respect, this is a fundamentally incorrect place to begin making your case. That is not what pixel aspect ratio means and I wonder if this misunderstanding is the cause of this entire issue. The pixel aspect ratio is the ratio of each individual pixel's width to its height. The total resolution is not relevant to the aspect ratio of an individual pixel, aka the pixel aspect ratio. Wikipedia has a [reasonably informative article](https://en.wikipedia.org/wiki/Pixel_aspect_ratio) if you want more information on what the term means, but I'll go into some more detail below.

To give a visual representation that's relevant to NES specifically, I'm going to blow up Mario's sprite to an exact 8:7 pixel aspect ratio, meaning **the size of each NES pixel has an 8:7 ratio**. Again, the resolution of the output image is not in any way related. I'll put gridlines on the sprite so that you can see for yourself the relative dimensions of the pixels.
<div align="center">

![mario87](https://github.com/punesemu/puNES/assets/5259025/98f542c3-4d07-4731-b7d7-3d3483bab412)
</div>

Take a look at the buttons on Mario's overalls, which are a single pixel each in Super Mario Bros. I'll blow one of those up again, still in the 8:7 pixel aspect ratio, with markings indicating the relative dimensions.
<div align="center">

![button87-labelled](https://github.com/punesemu/puNES/assets/5259025/e0348a34-53d2-4f96-8795-8284ac293e06)
</div>

With this understanding of what a pixel aspect ratio actually is, I will reiterate: this is the pixel aspect ratio of the NES hardware, and pixel aspect ratio refers to the *relative dimensions of each pixel*, **not** to the *image resolution*.

The **display aspect ratio**, which you have correctly understood, can be derived by multiplying the pixel aspect ratio by the width of the image, then dividing by its height. In the case of the NES, that's 256\*240 pixels, if we include the full frame (no overscan). That formula looks like this:

$$\frac{(8/7) \times 256}{240} \approx 1.2190476190476190476190476190476$$

Now, perhaps the confusion over what "pixel aspect ratio" means was hampering the understanding of the way which we both approached reaching a 4:3 aspect ratio, because we fundamentally did **exactly the same thing** by cropping 20 pixels total off of the top/bottom. So now, we'll check what the formula looks like if we go with our shared solution of taking 20 pixels off the top and bottom of the image:

$$\frac{(8/7) \times 256}{220} \approx 1.3298701298701298701298701298701$$

What do you know, it's 4:3.

I don't know if you need me to continue at this point, because that misunderstanding about pixel aspect ratios may be the root of this entire issue. But I'll assume that you still disagree, so allow me to go on.

## Birth of a scanline

> Aspect ratio is not preserved when the NES converts its digital signals to the analog signals that a CRT TV uses.

This is again based on a misunderstanding of pixel aspect ratios. The pixel aspect ratio **does not exist yet** when the image is all digital. It is the conversion from digital pixels to analog scanlines which **creates** the pixel aspect ratio. Again: the pixel aspect ratio is not **preserved** here, it is **created** here. When converting the purely digital pixels to an analog scanline, the NES has to plot those pixels sequentially as the scanline is generated. While a scanline is analog and has no "pixels", the pixels are the source data which make up the contents of that scanline. The rate at which the pixels are sampled determines how wide they will appear in the final scanline, and this is what we refer to as the pixel aspect ratio.

Hardware which needs to convert digital data to analog video, such as a video game console, must determine the rate at which the pixels are sampled, which in turn determines their width within the final scanline. On the NES and most similar platforms from the era, this is 5.37 MHz. According to the [PinEight wiki](https://pineight.com/mw/page/Dot_clock_rates.xhtml), some of the many platforms which share the same pixel clock include the ColecoVision, Sega Master System, Sega Mega Drive/Genesis (in H32 mode), TurboGrafx-16, SNES and even the PlayStation (when in its 256-wide mode). Given their wide use, this is a very well established and understood video signal.

The 5.37 MHz pixel clock in each of these platforms results in the same 8:7 **pixel aspect ratio** across all of them, but it's especially notable that this does not mean they all have the same **display aspect ratio**, because some of these platforms have different vertical resolutions which bring them closer to the 220 height which we both agreed results in a 4:3 image.

For this, the SNES is a great example. We now know that the SNES has the same 8:7 pixel aspect ratio as the NES, and we probably also know that while the SNES hardware is capable of displaying more than 224 lines and it's not *massively* uncommon for games to do so, **most** SNES games run at a resolution of 256\*224. That means it's formula time again:

$$\frac{(8/7) \times 256}{224} \approx 1.306122448979591836734693877551$$

Wahey, it's *basically* 4:3. You can still expect to lose some image to overscan (less than on NES games like Super Mario Bros. which fill the entire image), but the video signal output by the SNES has a ratio **extremely slightly** shy of true 4:3, which you won't notice on most TVs because of overscan. The rest of the scanlines are left blank, so you can still regard the SNES as running at 240p (not 224p), it's just that those extra scanlines aren't displaying anything interesting (sounds familiar). Many emulators will allow you to adjust that overscan either to suit 4:3 exactly or whatever else you prefer.

## A TV's job is never done

> The CRT TV stretches any input signal it receives to fill the screen

Not even once. The CRT TV displays the scanlines you tell it to display, nothing more and nothing less. You generate your scanlines, some areas of which you leave empty for horizontal blanks, overscan compensation, etc., then you feed those scanlines into the TV and it displays them. It does **not** guess how much of this scanline you want to be visible and resize its output to accommodate what it guessed you want, it just does its job: it shoots a stream of electrons at the phosphorescent layer on the back of the glass bit which match **whatever you told it to display**.

Does it help you to know that a scanline is in fact much wider than the visible portion of the scanline which the NES fills with picture? A single scanline runs for 341 PPU cycles. *In theory*, some NES-like hardware could plot 341 pixels into that scanline, although this would encroach on the horizontal blanking period (the time where the electron gun is moving back to the left to start the next line). The TV **does not know** which part of the scanline the NES is filling with picture and **does not guess either**. It will not **change** the image before output, that is not a TV's job and not how a TV functions. It will display the signal which you feed to it, determined by the pixel clock in the attached hardware and affected only by the geometry of the tube (CRT TVs tend not to have perfectly rectangular apertures) and the default-or-manually-calibrated tuning of that TV.

If I can quickly deviate from console hardware, you might be familiar with the service menus of arcade games, many of which include calibration screens that you can use to manually adjust the geometry settings of the machine's CRT monitor to fit the entire image onto the screen. This is necessary because the monitor (which is **essentially** a TV) has no idea how much of the scanline is real picture and how much is border. Just like TVs, they cannot guess. It's not their job to guess. They display what you tell them to and if you don't like it, you manually adjust the calibration.

> An 8:7, 3.66:3, or any other PAR source, when cropped and stretched to fill up a 4:3 display, will always result in a 4:3 picture.

Here you're mixing up PAR and DAR, which I think is explained by a Mesen setting we'll get to later. But yes, if you stretch an image to fit exactly 4:3 it will be 4:3, but as we just established, a TV will **not magically do this on its own** and **the aspect ratio you feed to the TV is the one it will display** (overscan aside). Fortunately, puNES lets you configure both your PAR and overscan to achieve this if it's what you want.

## Honestly, just read this part

> There are many incorrect statements made in the post above. I'll discuss only the "smoking gun" -- Kirby's Adventure.

The irony here is that your smoking gun is just **recreating the 8:7 PAR** and we're right back at the start. But I think this brings us to an important point of confusion. In puNES, you choose a pixel aspect ratio (the ratio of a pixel's width to its height), you do **not** choose a display aspect ratio. Mesen **mixes these together**, including options for each. It has options like "NTSC (8:7 PAR)" and "Standard (4:3)". The first one is a pixel aspect ratio and the second one is a display aspect ratio.

Here I'll make up a table of the most important **pixel and display** aspect ratios in both Mesen and puNES. I will assume **zero overscan** in all cases. I will keep all **display** aspect ratios relative to the height of 3 for ease of comparison.
<div align="center">

| Setting | Pixel Aspect Ratio | Display Aspect Ratio |
|:--|-:|--:|
| puNES 1:1 | 1:1 | 3.2:3 |
| puNES 5:4 | 5:4 | 4:3 |
| puNES 8:7 | 8:7 | 3.66:3 |
| Mesen Default (No Stretching) | 1:1 | 3.2:3 |
| Mesen Standard (4:3) | 5:4 | 4:3 |
| Mesen NTSC (8:7 PAR) | 8:7 | 3.66:3 |
</div>

Hopefully you can see the pattern here: these three settings are **identical** across the two emulators, they just use different names. puNES requires you to understand what a pixel aspect ratio is, while Mesen requires you to understand both **pixel** and **display** aspect ratios.

Next, let's talk about how Mesen handles overscan. The important thing to note is that it handles overscan **differently depending on which option you choose**. When you set NTSC (8:7 PAR), Mesen's goal is to preserve that **pixel** aspect ratio at all times. Increasing the overscan simply makes the window smaller, because there's less picture to show. The individual pixels' which remain visible will always be in the 8:7 pixel aspect ratio, but you are changing the **display** aspect ratio by adjusting the overscan.

However, when you set Standard (4:3), the nature of the emulator's overscan feature changes: now, Mesen's goal is to preserve the **display** aspect ratio regardless of the amount of overscan. The cropped image is stretched to fit 4:3 regardless of how much overscan you have on each side. You are changing the **pixel** aspect ratio by adjusting the overscan.

Now, if you're playing along at home, you might have just figured out what's going on here. When you first set Standard (4:3), the pixel aspect ratio is 5:4, which is not as tall as the accurate NES PAR (8:7). However, if you then cut 20 pixels off the screen using the overscan settings, Mesen will stretch the image *vertically*, resulting in taller pixels, bringing you back to the ideal 8:7 PAR.

Here is a recreation of your "smoking gun" in puNES. This is using the exact settings I described in my previous comment: 20 pixels of overscan and an 8:7 PAR. You may note that that's the same amount of overscan and PAR as you achieved in Mesen. In both cases, the result is a 4:3 image:
<div align="center">

![image](https://github.com/punesemu/puNES/assets/5259025/b0126c7f-5af7-478a-9a08-9d51715be2c8)
</div>

Somehow, we are managing to do exactly the same thing and still arguing about it anyway. Ultimately, the solution to achieving 4:3 is an 8:7 PAR and roughly 20 pixels of overscan. You just came at it from the opposite direction to me. You're starting with correct 4:3 display aspect ratio but the **wrong** PAR and simulating vertical overscan until you got the **correct** 8:7 PAR. I started with the correct 8:7 PAR and the **wrong** aspect ratio and simulated overscan until I got to the **correct** 4:3 display aspect ratio. It's the same thing.

## Overscan, again?

> @vaguerant's 3.66:3 screenshot, if placed directly on a 4:3 display would have black bars on the left and right

I explained on multiple occasions that overscan would hide the black bars, including literally directly below the image you're talking about. This is not sensible and I won't respond to it in any further detail.

## Ultimately ...

> I'm not asking that this be the only aspect ratio offered by puNES, but just an option for those of us looking for a more faithful recreation of the system. Would you please reopen this issue?

And I am explaining that puNES already does faithfully recreate the system, with results basically indistinguishable from Mesen to boot. 8:7 PAR, 20 pixels of overscan gets you a 4:3 image. What you're doing in Mesen is just a complicated way to get an 8:7 PAR, especially since the emulator already provides you that option out of the box.

I have a great deal of respect for your passion in this area, but this entire issue seems to hinge on one big misunderstanding of the difference between **resolution** and **pixel aspect ratio**, which are 100% unrelated. puNES is already doing what you want it to, as long as you understand what that is.

**Comment by possiblyneal** [comment]
You're right, I did have the definition of PAR incorrect. Knowing that helps me understand where you're coming from. Though that doesn't invalidate any of the conclusions that I made.

> You're starting with correct 4:3 display aspect ratio but the wrong PAR and simulating vertical overscan until you got the correct 8:7 PAR. I started with the correct 8:7 PAR and the wrong aspect ratio and simulated overscan until I got to the correct 4:3 display aspect ratio. It's the same thing.

If it's the same thing, how could one possibly be right and another be wrong? I prefer to select an option in an emulator that always gives me a 4:3 picture. I may not always want 20 pixels of vertical overscan. Many games show garbage or blank areas on the left and right of the screens. Overscan is an easy way to take care of this and I don't want it to adjust the final aspect ratio. It's also analogous to how you would adjust a real CRT TV set. So that's intuitive to me.

> I explained on multiple occasions that overscan would hide the black bars, including literally directly below the image you're talking about. This is not sensible and I won't respond to it in any further detail.

Wow.

>And I am explaining that puNES already does faithfully recreate the system

If you were genuinely trying to explain that, your first response would have simply told me to select the 5:4 option and briefly explained pixel aspect ratio and how it results in a 4:3 DAR. Instead, I received a rude and condescending lecture. Your posts are filled with patronizing and dismissive language. I can feel the frustration in your writing, likely stemming from some inadequacy or insecurity in your personal life. You are so angry that I disagree with you. To mask your own feelings of inadequacy, you come online to lecture and patronize internet strangers to fuel your false sense of superiority. Or maybe I'm wrong. Either way, you need to learn how to communicate without being condescending or dismissive. Otherwise, no one will want to communicate with you at all, and you'll push away everyone close to you, if you haven't already. I certainly won't be engaging with you any longer. Good luck.

**Comment by vaguerant** [comment]
I respect your non-engagement and will return it in kind. That said, I do wish to explain some details for the benefit of anybody else who finds this issue. Should any of the below disagree with you, please do not take it personally; I am not saying this in an attempt to hurt you in any way. I wish you all the best!

## The many ways to achieve 4:3
First up, I'll mention again that we're talking about an NTSC NES here, so all of the following figures will **not be accurate** for PAL or maybe Dendy NES either, since I don't know how those display.

If the goal is hardware-accuracy and a 4:3 display aspect ratio, **any approach which uses an 8:7 PAR** can be regarded as correct. This includes my (puNES) approach as laid out in my first comment and the (Mesen) approach laid out in possiblyneal's comment. Either are correct. There's also plenty of other ways to achieve the same or similar things: Mesen's NTSC TV (8:7 PAR) with 20 pixels of overscan will work, as will more exotic configurations. Here's an example config you can use in either emulator to get roughly a 4:3 display aspect ratio, with 8 pixels of overscan on the left side, while preserving the correct 8:7 PAR:

* Overscan
  * Up: 14
  * Down: 14
  * Left: 8
  * Right: 0
* Pixel Aspect Ratio
  * 8:7 (NTSC TV)

The final resolution this gives you is 248\*212. Of course, you can adjust how much overscan is simulated on the top vs. the bottom (e.g. Up: 18 and Down: 10) depending on your preference and the game in question. To check that this is giving us a 4:3 (1.33:1) display aspect ratio, we'll re-use our aspect ratio formula from earlier:

$$\frac{(8/7) \times 248}{212} \approx 1.3369272237196765498652291105121$$

If you know the **width** you want to use (e.g. 248, as above), you can use the formula below to determine what **height** is appropriate to achieve 4:3:
$$(3/4) \times (8/7) \times 248 \approx 212.57142857142857142857142857143$$

This gets you 212 and change; I decided to round down to an even 212. To get our overscan amount, we do `240 - 212 = 28`; hence the 14 overscan at top/bottom. Technically, rounding up to 213 is **even closer to exactly 4:3**, so you might want to go with 14 and 13 or some other overscan setup which adds up to 27.

Since you can't easily type the above formulas into a calculator, here's some versions you can copy-paste into Google, the Windows Calculator app in Scientific mode, or wherever you like to do your calculating to see what aspect ratio your setup has:
```
((8/7) * yourHeight) / yourWidth
(3/4) * (8/7) * yourWidth
```
## What about the other pixel aspect ratios?
All of the above is about hardware accuracy to the signal the NES outputs, but there's **no guarantee** that your personal TV either back then or now was perfectly calibrated, either from the factory, any custom setup applied to your TV, misalignments picked up over time on an aging set, etc. Alternatively, you might not care *at all* what NES games looked like on a CRT in 1985 and have a goal that doesn't connect with any of this stuff.

Using a pixel aspect ratio **other** than 8:7 (such as puNES's 1:1 or 5:4) **won't** be an ideal simulation of a correctly calibrated NTSC CRT TV--*say that five times fast*--but if it looks good to you or gives you nostalgic feelings because it's how you remember things looking on your childhood TV, then just use that setting. You're trying to have fun, not take a math class. In fact, 1:1 and 5:4 are especially advantageous pixel aspect ratios for a number of reasons.

1:1 gives you that clean "**pixel-perfect**" look, similar to how pixel art is often presented in modern indie games (or on semi-modern handhelds like the Game Boy Advance through PS Vita). These square pixels can look super nice, and (as noted in a prior comment) it was much easier for artists to design as though each pixel of each tile is a perfect square than to account for the native 8:7 pixels. **Occasionally**, games go out of their way to handle this (e.g. Samus's Morph Ball sprite in Metroid is 7\*8 pixels, because the PAR will correct him--*no spoilers!*--back into a proper circle; Dr. Mario's decorative magnifying glass is similarly tuned for 8:7) but **many games don't do this** and will simply look more natural with 1:1 pixels. It really depends on the game.

5:4 gives you an **exact 4:3 image** without needing any overscan at all, while sort-of semi-approximating the correct 8:7 pixels with somewhat wider ones. An additional benefit is that you don't need a UHD monitor to do this at a pixel-perfect scale. You can do a 5x horizontal/4x vertical scale in 1280\*960 pixels, which is a pretty acceptable fit on a 1080p display. This is a great option if you want the benefit of clean (**integer-scaled**) pixels while also approximating the pixel aspect ratio of a real NES.

## Go play games
In a bunch of wildly inaccurate aspect ratios just because you feel like it. That's what I'm gonna do.
