### ISSUE TITLE
Arabic Translation

### ISSUE THREAD

**Issue by Chipsum** [punesemu/puNES#330]
Hi
I tired to pull request, but seems I can't, anyway

for the first time, puNES gets a Arabic translation, Congrats !
[ar_AR.zip](https://github.com/punesemu/puNES/files/13171239/ar_AR.zip)
[flag_arabic.zip](https://github.com/punesemu/puNES/files/13171450/flag_arabic.zip)
[flag_arabic (2).zip](https://github.com/punesemu/puNES/files/13171552/flag_arabic.2.zip)

**Comment by punesemu** [comment]
ManyThx Chipsum!! This weekend I will add your translation and if you want to update or improve it you will do so on [https://crowdin.com/project/punes](https://crowdin.com/project/punes).

**Comment by Chipsum** [comment]
@punesemu Thank you very much it sounds amazing, I have a lot of terms that needs work on. ❤️

**Comment by punesemu** [comment]
Hi Cipsum, I took a look at your ar_AR.ts file but unfortunately I can't import it into the emulator because it is not in the correct format. From looking at it, I understand that you took the en_EN.ts file and started translating it using an editor but unfortunately you translated the <source> tags but this is not correct. You should not translate the <source> tags and you needed to insert the translation in the <translation> tag, if you had taken a look at one of the other translations you would have noticed this. Unfortunately, your file is unusable to me. I added the Arabic language on Crowdin and if you still want to contribute, you can use the platform. It will be easier to maintain and update. I thank you anyway for your wonderful contribution.

**Comment by Chipsum** [comment]
Hi @punesemu , I see, Okay no problem, I will translate it again one by one till it's ready 👍

**Comment by Chipsum** [comment]
I understand, I still can program in my tool something to get things from source to translation tag.
![image](https://github.com/punesemu/puNES/assets/37517008/4e4aa2de-4dfc-47ee-a71c-0150cfacfe67)

**Comment by Chipsum** [comment]
Thank you for the explanation.
Leave it to me, I will use Crowdin till it's ready :D

**Comment by Chipsum** [comment]
@punesemu I am so Sorry I forgot these ones:

The virtual keyboards, Subor and Family basic keyboards
the controls in red
![image](https://github.com/punesemu/puNES/assets/37517008/d14dd978-efc4-44b5-9e2d-74414d863653)
![image](https://github.com/punesemu/puNES/assets/37517008/72e383cc-d9ab-4a68-aa4d-a09bb344a9d3)
