### ISSUE TITLE
Update NesDev thread, and add WIP links to "Releases" page 

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#356]
Hi. I'm opening this issue as a reminder for you to update [this thread on NesDev.org](https://forums.nesdev.org/viewtopic.php?t=6928). You haven't updated it in a while, and the download links there still point to very old builds. Since it's a forum for developers, maybe you could replace them with the WIP links.

You could also add the WIP links to the [Releases page](https://github.com/punesemu/puNES/releases) with a sticky post tagged as `Pre-release` (there are repositories that do this by uploading dummy zip files). Some potential contributors and testers aren't aware of the WIP builds (example: #332).

**Comment by RokkumanX** [comment]
I concur on this on so many levels, good calling on this @anewuser 
Also, the last post from anyone on the puNES emulator thread was on **Wed Feb 17, 2021 12:56 pm** which is almost 3 years ago!!!

@punesemu 

Let me tell you a story of how puNES, a wonderful little accurate NES/Famicom/Famicom Disk System emulator came into my life.

It all started back in august 2013 and it was a time where I didn't really had made up my mind of which NES emulator I wanted to go with casually.

I had Nestopia Undead ver 1.45 and Jnes 1.1.1 (from Jabo, the guy that created plugins for Project64) to play with.
Accuracy for Nestopia at the time was around 79,6% and Jnes with it's measly 13,4%

No sir, I needed more so I began to search high and low for an emulator that could surpass Nestopia.
Oh yeah, I found a little forum called forums.nesdev.org and under NESemdev there was this thread called puNES Emulator created by a guy named FHorse.

Those new to puNES must remember that this was in a time before GitHub and most projects were open sourced like to day, also Mesen wasn't around either.

Many people didn't like that puNES was closed sourced back then, but oh boy when I tried puNES 0.68 (a version which is ancient today) I was totally blown away by it's superb accuracy.

Astonishing 92,3% according to [TASVideos NESAccuracyTests](https://tasvideos.org/EmulatorResources/NESAccuracyTests) (It's 98,8% today)

From that day forward I made puNES to my NES equivalent as to bsnes for SNES.

puNES have come a long way since I started using it back in 2013 and the gap between puNES and Mesen isn't big at all.

So FHorse, please consider updating the puNES Emulator thread because it deserves a better fate than dying now that I have given you an awesome (100% true) story.

Have a nice day!

**Comment by RokkumanX** [comment]
I concur on this on so many levels, good calling on this @anewuser 
Also, the last post from anyone on the puNES emulator thread was on **Wed Feb 17, 2021 12:56 pm** which is almost 3 years ago!!!

@punesemu 

Let me tell you a story of how puNES, a wonderful little accurate NES/Famicom/Famicom Disk System emulator came into my life.

It all started back in august 2013 and it was a time where I didn't really had made up my mind of which NES emulator I wanted to go with casually.

I had Nestopia Undead ver 1.45 and Jnes 1.1.1 (from Jabo, the guy that created plugins for Project64) to play with.
Accuracy for Nestopia at the time was around 79,6% and Jnes with it's measly 13,4%

No sir, I needed more so I began to search high and low for an emulator that could surpass Nestopia.
Oh yeah, I found a little forum called forums.nesdev.org and under NESemdev there was this thread called puNES Emulator created by a guy named FHorse.

Those new to puNES must remember that this was in a time before GitHub and most projects were open sourced like to day, also Mesen wasn't around either.

Many people didn't like that puNES was closed sourced back then, but oh boy when I tried puNES 0.68 (a version which is ancient today) I was totally blown away by it's superb accuracy.

Astonishing 92,3% according to [TASVideos NESAccuracyTests](https://tasvideos.org/EmulatorResources/NESAccuracyTests) (It's 98,8% today)

From that day forward I made puNES to my NES equivalent as to bsnes for SNES.

puNES have come a long way since I started using it back in 2013 and the gap between puNES and Mesen isn't big at all.

So FHorse, please consider updating the puNES Emulator thread because it deserves a better fate than dying now that I have given you an awesome (100% true) story.

Have a nice day!

**Comment by punesemu** [comment]
Thank you so much for the kind words, it's nice to have some appreciation sometimes. I promise I will update the thread when I release the new version

**Comment by RokkumanX** [comment]
Congratulations to the new v0.111 release @punesemu  Tres bien!

I'll be looking forward to see an updated thread in the NesDev forums soon!
