### ISSUE TITLE
Jikai Shounen Met Mag - error loading save states

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#387]
Hello. `Jikai Shounen Met Mag (Japan).qd` freezes when I try to load save states.

[save.zip](https://github.com/punesemu/puNES/files/14671974/save.zip)

https://github.com/punesemu/puNES/assets/6733770/4674cad9-a006-405a-9d21-9bc682538903

puNES D3D9 b6dc62f
Windows 10

**Comment by Chipsum** [comment]
I noticed that even without save files it freezes when using rewind

**Comment by punesemu** [comment]
Good morning both of you, can you try with the new WIP?

**Comment by Chipsum** [comment]
Good morning, Fabio :D I hope you are doing great!
With the last WIP, in my case, the rewind is fixed, with a minor problem: when rewinding to some point just after the data is read from the disk side, it freezes until I rewind it a little back until I get the reading disk side again, then it continues to work.
I think rewinding with FDS needs a good investigation, which may be time-consuming for now, but **overall**, it's **working**.

About the saves, I have no idea yet since I was unable to reproduce.

**Comment by anewuser** [comment]
@punesemu It seems to be working fine now. Thank you!

**Comment by punesemu** [comment]
>Good morning, Fabio :D I hope you are doing great!
With the last WIP, in my case, the rewind is fixed, with a minor problem: when rewinding to some point just after the data is read from the disk side, it freezes until I rewind it a little back until I get the reading disk side again, then it continues to work.
I think rewinding with FDS needs a good investigation, which may be time-consuming for now, but overall, it's working.

Hi @Chipsum, I did some tests but I couldn't reproduce the problem, can you give me some more information?
