### ISSUE TITLE
Some unlicensed games are not working

### ISSUE THREAD

**Issue by ghost** [punesemu/puNES#46]
The following games are not working as expected:

Hard Drivin' (USA) (Proto) (Unl) - Error Loading Rom
Hell Fighter (Asia) (PAL) (Unl) - Illegal Opcode
Hidden Chinese Chess - An Qi (Asia) (NTSC) (Unl) - Error Loading Rom
Metal Fighter (Asia) (Sachen) (Unl)
Ms. Pac-Man (USA) (Unl)
Othello (Australia) (Unl) - Error loading Rom
Policeman (Spain) (Gluk Video) (Unl) - Mapper 36
Popo Team (Asia) (Unl)
Pyramid II (Asia) (PAL) (Unl) - Black Screen
Racermate Challenge II (USA) (All Versions) (Unl) - Mapper 168
Rockball (Asia) (Unl) - Black Screen
Secret Scout in the Temple of Demise (USA) (Beta) (Unl)
Sidewinder (Asia) (PAL) (Unl)
Sidewinder (Australia) (Unl) - Error Reading Rom
Silent Assault (Asia) (PAL) (Unl) - Illegal Opcode
Silver Eagle (Asia) (PAL) (Unl) - Black Screen
Street Heroes (Asia) (Unl) - Gray Screen
Super Cartridge Ver 1 - 4 in 1 (Asia) (Unl) - Black Screen
Super Cartridge Ver 2 - 10 in 1 (Asia) (Unl) - Black Screen
Super Cartridge Ver 3 - 8 in 1 (Asia) (Unl) - Black Screen
Super Cartridge Ver 4 - 6 in 1 (Asia) (Unl) - Illegal Opcode
Super Cartridge Ver 5 - 7 in 1 (Asia) (Unl) - Illegal Opcode
Super Cartridge Ver 6 - 6 in 1 (Asia) (Unl) - Black Screen
Super Cartridge Ver 7 - 4 in 1 (Asia) (Unl) - Black Screen
Super Cartridge Ver 8 - 4 in 1 (Asia) (Unl) - Black Screen
Super Cartridge Ver 9 - 3 in 1 (Asia) (Unl) - Illegal Opcode
Super Pang (Asia) (PAL) (Unl)
Super Pang II (Asia) (Unl)
Taiwan Mahjong - Tai Wan Ma Que 16 (Asia) (Unl)
Twin Eagle (Asia) (PAL) (Unl)
AV Super Real Pachinko (Japan) (Unl)

Block Out (USA) (Proto)
Elite (Unknown) (NTSC Demo)
Bugs Bunny Birthday Bash (USA) (Beta) [b] - Illegal Opcode
Secret Scout in the Temple of Demise (USA) (Beta) (Unl)

**Comment by punesemu** [comment]
Hi PinkLouie, where can I find these roms?

**Comment by PinkLouie** [comment]
All these roms are No-Intro roms. You can find them in the "Paradise". I don't know if I can post a link to piracy, if is it allowed.

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/2bb3d26f7ae9ae36afe3d11f789cb32e60f0fa93

Hard Drivin' (USA) (Proto) (Unl).nes Missing header, impossible to fix
Hell Fighter (Asia) (PAL) (Unl).nes - Incorrect header, fixed in database
Hidden Chinese Chess - An Qi (Asia) (NTSC) (Unl).nes - Incorrect header, fixed with the support for the truncated PRG ROM
Metal Fighter (Asia) (Sachen) (Unl).nes - Incorrect header, fixed in database
Ms. Pac-Man (USA) (Unl).nes - Incorrect header, fixed in database
Othello (Australia) (Unl).nes - Incorrect header, fixed with the support for the truncated PRG ROM
Policeman (Spain) (Gluk Video) (Unl).nes - Added support for mapper 36
Popo Team (Asia) (Unl).nes - Incorrect header, fixed in database
Pyramid II (Asia) (PAL) (Unl).nes - Incorrect header, fixed in database
Racermate Challenge II (USA) (All Versions) (Unl).nes - Run well but, to play, it's necessary to emulate the controller specific for this game. I honestly don't know if it has ever been emulated. More info at http://www.nesmuseum.com/racermate.html
Rockball (Sachen) [!].nes - Incorrect header, fixed in database
Secret Scout in the Temple of Demise (USA) (Beta) (Unl).nes - This beta don't support bus conflict, fixed in database
Sidewinder (Asia) (PAL) (Unl).nes - Incorrect header, fixed in database
Sidewinder (Australia) (Unl).nes - Incorrect header, fixed in database
Silent Assault (Asia) (PAL) (Unl).nes - Incorrect header, fixed in database
Silver Eagle (Asia) (PAL) (Unl).nes - Incorrect header, fixed in database
Street Heroes (Asia) (Unl).nes - Incorrect header, fixed in database
Super Cartridge Ver 1 - 4 in 1 (Asia) (Unl).nes - Incorrect header, fixed in database
Super Cartridge Ver 1 - 4 in 1 (Asia) (Unl).nes - Incorrect header, fixed in database
Super Cartridge Ver 2 - 10 in 1 (Asia) (Unl).nes - Incorrect header, fixed in database
Super Cartridge Ver 3 - 8 in 1 (Asia) (Unl).nes - Incorrect header, fixed in database
Super Cartridge Ver 4 - 6 in 1 (Asia) (Unl).nes - Incorrect header, fixed in database
Super Cartridge Ver 5 - 7 in 1 (Asia) (Unl).nes - Incorrect header, fixed in database
Super Cartridge Ver 6 - 6 in 1 (Asia) (Unl).nes - Incorrect header, fixed in database
Super Cartridge Ver 7 - 4 in 1 (Asia) (Unl).nes - Incorrect header, fixed in database
Super Cartridge Ver 8 - 4 in 1 (Asia) (Unl).nes - Incorrect header, fixed in database
Super Cartridge Ver 9 - 3 in 1 (Asia) (Unl).nes - Incorrect header, fixed in database
Super Pang (Asia) (PAL) (Unl).nes - Incorrect header, fixed in database
Super Pang II (Asia) (Unl).nes - Incorrect header, fixed in database
Taiwan Mahjong - Tai Wan Ma Que 16 (Asia) (Unl).nes - Incorrect header, fixed in database
Twin Eagle (Asia) (PAL) (Unl).nes - Incorrect header, fixed in database
AV Super Real Pachinko (Japan) (Unl).nes - Sorry but I don't find this rom

Block Out (USA) (Proto).nes - Missing header, impossible to fix
Elite (Unknown) (NTSC Demo) - What is not working?
Bugs Bunny Birthday Bash (USA) (Beta) [b].nes - I didn't find a single emulator that run it. Possible bad dumps?

**Comment by PinkLouie** [comment]
I think Block Out (USA) (Proto) was fixed in NesHawk. Not released yet in a stable version.
Elite is bugged. It works in Mesen
I attached AV Super Real Pachinko in the comment.

![image](https://user-images.githubusercontent.com/24971871/26998646-271af7f6-4d5d-11e7-841a-50ffc93e05f0.png)
[AV Super Real Pachinko (Japan) (Unl).zip](https://github.com/punesemu/puNES/files/1065501/AV.Super.Real.Pachinko.Japan.Unl.zip)

Also, some licensed game are not working. They are:

Galaxian (Japan)
Galaxian (Japan) (Rev A)
Mississippi Satsujin Jiken (Japan) (Rev A)
Money Game, The (Japan) - Black Screen
Tatakae!! Rahmen Man - Sakuretsu Choujin 102 Gei (Japan) - Black Screen with sound of old TVs with no signal.
Mighty Bomb Jack (Japan) (Rev A) - Black Screen
Dragon Ball 3 - Gokuu Den (Japan) (Rev 1)
Super Mario Bros. 25 Shuunen Version (Japan) (En) (Promo, Virtual Console)

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/92cdde195b85ec3c5e66e660fd81fbfed1895715

Block Out (USA) (Proto).nes - This version is a bad dump, the version running on neshawk (with PRG ROM sha1 2500B5492ECE1CAFB97881C5A384B0768313BF98) runs perfectly with puNES, tested and verified
Elite is bugged. It's a Pal rom - Incorrect header, fixed in database
AV Super Real Pachinko (Japan) (Unl).nes - Missing header, impossible to fix
Galaxian (Japan).nes - Bad dump, the rom must be at least 16kb (http://bootgod.dyndns.org:7777/profile.php?id=1808)
Galaxian (Japan) (Rev A).nes - Bad dump, the rom must be at least 16kb (http://bootgod.dyndns.org:7777/profile.php?id=1808)
Mississippi Satsujin Jiken (Japan) (Rev A).nes - Incorrect header, fixed in database
Money Game, The (Japan).nes - The version that I've runs well
Tatakae!! Rahmen Man - Sakuretsu Choujin 102 Gei (Japan).nes - The version that I've runs well
Mighty Bomb Jack (Japan) (Rev A).nes - Added to database
Dragon Ball 3 - Gokuu Den (Japan) (Rev 1).nes - Missing header, impossible to fix
Super Mario Bros. 25 Shuunen Version (Japan) (En) (Promo, Virtual Console).nes - Missing header, impossible to fix
Mahjong (Japan) - The only versions that I've found are : Mahjong (Japan) (Rev A).nes and Mahjong (Japan) (Rev B).nes and both runs well
Miracle Piano Teaching System, The (France).nes - Incorrect header, fixed in database
Dragon Quest II - Akuryou no Kamigami (J-VC) - I can't find this rom
Dragon Quest III - Soshite Densetsu e... (J-VC) (PRG1) - I can't find this rom
Gradius II (J) (VC) - Grey Screen - I can't find this rom
Kage no Densetsu (J) (VC) - I can't find this rom
Street Gangs (E) (VC) - I can't find this rom
Banana (1986-09-08)(Victor Ongaku Sangyou)(JP).nes - Tosec - I think that is a bad dump, http://bootgod.dyndns.org:7777/profile.php?id=2690 as you can see, CHR ROM should have a size of 16Kb while this rom has 8kb
Captain Skyhawk (1989)(Rare)(PlayChoice-10) - Tosec - Fixed in database
Mario's Open Golf (1991)(Nintendo)(PlayChoice-10) - Tosec - Fixed in database

Mei Shao Nv Meng Gong Chang (Princess Maker) (Sachen) (Unl) [U][!].unif - Runs well here

**Comment by PinkLouie** [comment]
Here are the files for you:
[Mahjong (Japan).zip](https://github.com/punesemu/puNES/files/1069523/Mahjong.Japan.zip)
[Money Game, The (Japan).zip](https://github.com/punesemu/puNES/files/1069517/Money.Game.The.Japan.zip)
[Tatakae!! Rahmen Man - Sakuretsu Choujin 102 Gei (Japan).zip](https://github.com/punesemu/puNES/files/1069518/Tatakae.Rahmen.Man.-.Sakuretsu.Choujin.102.Gei.Japan.zip)
[Dragon Quest II - Akuryou no Kamigami (J-VC).zip](https://github.com/punesemu/puNES/files/1069529/Dragon.Quest.II.-.Akuryou.no.Kamigami.J-VC.zip)
[Dragon Quest III - Soshite Densetsu e... (J-VC) (PRG1).zip](https://github.com/punesemu/puNES/files/1069532/Dragon.Quest.III.-.Soshite.Densetsu.e.J-VC.PRG1.zip)
[Gradius II (J) (VC).zip](https://github.com/punesemu/puNES/files/1069538/Gradius.II.J.VC.zip)
[Kage no Densetsu (J) (VC).zip](https://github.com/punesemu/puNES/files/1069541/Kage.no.Densetsu.J.VC.zip)
[Street Gangs (E) (VC).zip](https://github.com/punesemu/puNES/files/1069544/Street.Gangs.E.VC.zip)
[Mei Shao Nv Meng Gong Chang (Princess Maker) (Sachen) (Unl) [U][!].zip](https://github.com/punesemu/puNES/files/1069545/Mei.Shao.Nv.Meng.Gong.Chang.Princess.Maker.Sachen.Unl.U.zip)

**Comment by punesemu** [comment]
Mahjong (Japan).zip - Missing header, impossible to fix
Money.Game.The.Japan.zip - Runs well here
Tatakae.Rahmen.Man.-.Sakuretsu.Choujin.102.Gei.Japan.zip - Runs well here
Dragon Quest II - Akuryou no Kamigami (J-VC).zip - Bad dumps?
Dragon Quest III - Soshite Densetsu e... (J-VC) (PRG1).zip - Bad dumps?
Gradius II (J) (VC).zip - Incorrect header, fixed in database (with the next commit)
Kage no Densetsu (J) (VC).zip - Incorrect header, fixed in database (with the next commit)
Street Gangs (E) (VC).zip - The roms runs well except for the first initial screen. Possible bad dump
Mei Shao Nv Meng Gong Chang (Princess Maker) (Sachen) (Unl) [U][!].zip - Runs well here

**Comment by PinkLouie** [comment]
Thanks for your time to fix these games.

**Comment by PinkLouie** [comment]
I tried them in version, 0.100. You make one of the best nes emulators available. Just needs a new stable release. :p

**Comment by anewuser** [comment]
Your lists have a mix of GoodNES (part of GoodTools) and No-Intro ROMS. 

GoodTools uses tags such as (J),  (U), (E) and [!], and lists all possible versions of a ROM, including hacks and old bad dumps, which means several gigabytes of garbage if you consider all systems. 

No-Intro uses tags such as (Japan), (USA) and (Europe) and focuses on cataloging only the best dumps for each release: officially released licensed and unlicensed games, and official test (beta) versions. The only "bad" ROMs listed by No-Intro are those that haven't been dumped properly yet. Those are marked with [b].

You should only use No-Intro sets, and [use clrmamepro to remove unwanted regional variants](https://www.reddit.com/r/RetroPie/comments/5njtvs/guide_how_to_trim_your_romset_of_duplicate_roms/).

**Comment by PinkLouie** [comment]
Yes, but actually most unlicensed nes roms found in No-Intro contains bad headers. A lot of No-Intro roms are not verified, so if it's a bad dump, you can't know without checking datomatic

**Comment by anewuser** [comment]
The only unlicensed cartridges I care about are two that I personally own physical copies of, but you can tell it by the [b] in the filename. 

You're supposed to clean up your set with clrmamepro before even considering trying to run the ROMs or creating issues on repositories. I only mentioned regional releases, but it also fixes file names to the most current No-Intro database and verify their integrity, so [b] is added to the ROMs that you shouldn't even try to open because they are known not to work.

In case you find a dump listed by No-Intro that isn't marked with [b], but definitely is problematic, you're supposed to report it to the project, so that everybody will benefit from this while cleaning their sets in the future.

**Comment by PinkLouie** [comment]
I am not supposed to clean anything, because when you do this you miss a lot of roms who can be problematic and not work, and each people clean in their personal way. And actually, some (b) works. And yeah, I already have reported errors to No-Intro, and changes were made. Some games missing in No-Intro are available in Goodset, and thanks to my reports they were added to No-Intro. Don't go saying what someone should or not do.

**Comment by anewuser** [comment]
You're free to do whatever you want. I just taught you what is the expected rational behavior.

You can keep all the garbage you want, but don't create issues on repositories expecting developers to guess what files you have and test ROMs that may be known to be broken by the community.

The time spent on guessing what you specifically have on your machine could be used on features and fixes that benefit hundreds of people.

**Comment by jcdenton2k** [comment]
**@anewuser** 

I fully understand your sentiment and I feel that I also understand where you are coming from.  However, you should be wary in trying to 'moderate' places like this.  The dev is able to handle things and it doesn't seem like they are being flooded with issues at the moment.

That said...

**@PinkLouie** 

You should do some decent due-diligence in verifying that your rom dump will work on an official NES (top loader model) or Famicom.  If you are unable or unwilling to do this then it may not be necessary to add specific exemptions for each and every unlicensed ROM you happen to find floating around online.  There's already an 'Unlicensed Games Wiki' that catalogs a lot of these wierd and crazy games.

It is pretty rude and overtly hostile to be so dismissive when someone asks you to follow proper and respectful decorum for submitting issues with accurate information.  Many of the ROMs you've claimed weren't working have turned out to be unworking bad dumps with bad data or missing data.  You are indeed wasting the dev's time with such things because you are too lazy or ignorant to follow some decent amount of respect for the limited time that a dev has.

Feel free to continue reporting but also mention how you attempted to verify dumps on your end to make sure they consisted of actual decent data.  No-Intro RomSets seem to be the gold standard when it comes to these types of things.  GoodNES was mostly used for those of us in the romhacking community but it quickly spiraled out of control with adding every possible 'bad dump' and overdump and whatever variation out there.

**Comment by anewuser** [comment]
@punesemu Now that Galaxian is fixed, the latest No-Intro dumps for the ROMs mentioned on this other page also seem to be all working fine on puNES.
