### ISSUE TITLE
Xaudio2 problem

### ISSUE THREAD

**Issue by ghost** [punesemu/puNES#47]
When I try to open PUnes I get this error. I use Windows 10, which have DX11.

![2017-05-25 8](https://cloud.githubusercontent.com/assets/24971871/26474778/7b29886a-4189-11e7-9ab6-0868287fabfa.png)

It was fixed when I installed Dx9. But it shouldn't be necessary, should it? Dx9 is not officially support by Win 10, and is very old. Also, the message mentions Dx10.

**Comment by jcdenton2k** [comment]
Many games and older programs still use DX9.  You'll have to install it anyways and broad-compatibility would require DX9 support instead of something that would exclude older platforms.
NES games aren't 3D (for the most part) and don't require a lot of the fancy features of DX10/DX11.  Most of those features are geared towards 3D rendering which is not applicable to puNES.
