### ISSUE TITLE
Libretro port?

### ISSUE THREAD

**Issue by ADormant** [punesemu/puNES#6]
What do you think about a libretro/RetroArch port? That way it'd be able to use Dynamic Rate Control Shaders etc
https://github.com/libretro/RetroArch

**Comment by punesemu** [comment]
Maybe in the near future.

**Comment by punesemu** [comment]
With regard to shaders, I'm having fun adding full support to the meta-shader used by Retroarch. For now the OpenGL engine is done. [Commit 3a18faf4ad62c46906a5b26decbb6d43ae240ea8](https://github.com/punesemu/puNES/commit/3a18faf4ad62c46906a5b26decbb6d43ae240ea8)

**Comment by SigmaVirus** [comment]
@punesemu 
The new OpenGL engine and the shaders are working great here on my end on WIP 099!
I'm looking forward to be able to choose which shader to use through file as I'm doing with Palettes today in the final release.

Currently I'm using Firebrandx's palette which is very faithful to what came out through Composite and sometimes I use the 3DS_VC palette.

I'm just glad puNES have gotten this far, sometimes I even forget that I'm using an emulator when I'm playing my Famicom and Famicom Disk System library with my iBuffalo Famicom USB controller or my original NES controller with an Retrobit adapter.

Keep up the good work!

**Comment by punesemu** [comment]
I really like Firebrandx's palettes, I think that I will include in the emulator. Thank you for the tip.

**Comment by ADormant** [comment]
@punesemu Now that you ported shaders perhaps it would be possible to implement DRC in punes?

https://github.com/libretro/RetroArch/wiki/Getting-optimal-vsync-performance

**Comment by ADormant** [comment]
https://github.com/libretro/RetroArch/tree/master/audio

**Comment by punesemu** [comment]
From what I understand, the development team of libretro are not interested in porting then I consider closed this ticket.

**Comment by fr500** [comment]
Who said libretro is not interested?
If anything, we always want upstream support directly instead of having to port stuff over by ourselves.

Not sure what gave you that idea, there's a lot of drama and fearmongering surrounding libretro.

**Comment by punesemu** [comment]
Hi Andrés, first of all there was no polemics in my words. I started this project to learn how to program in C and saw the love I feel for the emulators, I said to myself "why not try?". I never thought that someone else would use the emulator other than me or that I would come to have a github account for the project. I thought you were not interested because some users have reported to me some comments that have led me to think that. Not a problem, the criticism is welcome, and I take for granted that the emulator does not like to many for various reasons.

> If anything, we always want upstream support directly instead of having to port stuff over by ourselves.

I agree, I think it is the most reasonable solution.

> there's a lot of drama and fearmongering surrounding libretro.

:smile: You are right : [4chan comments](https://boards.fireden.net/_/search/text/punes/). Sure you have a slew of hardcore fans (it was a shock for me to discover that 95% of puNES code was taken directly from retroarch :scream:, at least the porting should be really simple). Jokes apart, really mine was not a polemic and pleased to know that I was wrong.

**Comment by twinaphex** [comment]
Please don't take anything you read in that 4chan emugen thread as gospel. 

We have lost many devs who would have liked to work with us simply because of comments made there which really don't reflect my attitude or stance towards these devs. 

I only hang out on IRC freenode at #retroarch and anything else you read about regarding me or what I say about stuff is simply hearsay. I'd encourage devs at least not to read that board and think anything being said on there is necessarily true, there are too many people at this point who simply like to instigate or try to create rifts. For what reasons I don't know, but it happens regardless.

**Comment by RodentVienna** [comment]
I'd be all trigger happy to at one day use puNES as libretro module in both retroarch on windows, and lakka on raspbberry pi. I love puNES and its the only emulator besides scummvm I use outside retroarch currently. I am all fired up you are considering it, and not rejecting the idea at all. Thank you!

**Comment by nco2k** [comment]
me too. i would love to use it in retroarch.

**Comment by jcdenton2k** [comment]
I would enjoy seeing puNES ported over to RetroArch as long as the drama llamas can be tamed ;)
4chan is a cesspool and frankly Reddit isn't usually much better.  Take what you hear about others with skepticism.

**Comment by DukeJP** [comment]
A libretro port would be nice to use, for the http://retroachievements.org site. The other nes cores arent to good, and puNES is close to be the best nes emu in accuracy.

**Comment by fr500** [comment]
Well I started a port.

I'm making a few assumptions, I think the main emulator is implemented in emu.c.
Problem is as far as I can see (correct me if I'm wrong) there is a lot of gui.h dependent code in emu.c.

Usually the process for me was directly calling core functions like:

`emu_load_rom`

or 

`emu_frame`

But it seems in this particular case I need to make libretro an alternate gui implementation?
It makes the process a lot more complicated.

**Comment by WizLizard** [comment]
@fr500 How is the port coming? Can we expect an official release anytime soon? I've been hoping for this for a while!

**Comment by fr500** [comment]
I haven't progressed at all, I didn't understand it all, it was a bit like (maybe I'm wrong) the core and the gui are co-dependent.

**Comment by WizLizard** [comment]
Keep trying man you can get it! A lot of people want this!

**Comment by WizLizard** [comment]
@fr500 Maybe FHorse could give you a hand lol?

**Comment by Pulfer** [comment]
Any news about it?

**Comment by fr500** [comment]
Nope, at least not on my side. I don't consider fostering libretro a good thing anymore
