### ISSUE TITLE
[Feature Request] Add support for QuickDisk format

### ISSUE THREAD

**Issue by Anuskuss** [punesemu/puNES#80]
> Games dumped off the Famicom Disc System come into two major types:
> - **.fds format**: Most common format. Ubiquitous in ROM sets (GoodSets, No-Intro). Omits some checksum data.
> - .**qd format** (stands for QuickDisk): Only ever used in official Nintendo re-releases. Almost identical to fds, but a full dump with checksum data. May omit padding.
>
> The checksum data in question would be checked at BIOS startup to verify the integrity of the image and whether it was tampered with, in which case it will throw an anti-piracy error. As of now, no NES emulators support the alternate more complete dumps, as well as fudging that check's result to always return a negative. To emulate a .qd image, stripping the checksum data with a custom script is needed.
>
>— [Emulation General Wiki](http://emulation.gametechwiki.com/index.php/Nintendo_Entertainment_System_emulators#QD_FDS_Support)

See this script for more information:
https://gist.github.com/einstein95/6545066905680466cdf200c4cc8ca4f0

**Comment by RokkumanX** [comment]
Reading through this [thread](https://forums.nesdev.com/viewtopic.php?f=2&t=15792) made me wonder if there is any benefit from using QuickDisk format dumps at all?

While it would be great that puNES could run QuickDisk format dumps, I highly doubt there is any real demand for it?

I own 14 Famicom Disk System games and I got them dumped in .fds format some time ago, been playing them happily ever since in puNES, some needed cleaning through Nestopia though.

Most people like me that were interested in Famicom Disk System games have probably already dumped them by now.

But out of curiosity I'm interested to see if there is any further demand for this.

**Comment by Anuskuss** [comment]
Benefit? Not really; the QD dumps (found inside official Nintendo games like the Zelda Collection) are almost identical to their FDS counterpart. It's just another format **but** in the name of preservation, it's necessary to support it IMHO.

**Comment by RokkumanX** [comment]
I hear you and I understand you.

And it would be great if puNES also supported proper FDS dumps.
Proper FDS dumps consists of 3 types of files:

.raw which is so called low-level dumps (MFM or Magnetic Flux)

.bin which is kinda like .fds but it also includes the CRC and gap data that the old .fds dumps were missing.

.fds files are normal FDS files that work in all FDS emulators.

We'll see if there is any chance for this.

**Comment by punesemu** [comment]
Quick Disk format is supported (fd482aa).
