### ISSUE TITLE
Konami Wai Wai World glitches (VRC2 Mapper 23 related)

### ISSUE THREAD

**Issue by SigmaVirus** [punesemu/puNES#9]
There seems to be some glitches during the vertically-scrolling part of the game as seen here:

![punes error](https://cloud.githubusercontent.com/assets/14175085/14067749/329ca584-f46c-11e5-88a5-3d75baeb3e07.png)

This is easy to re-produce and all you have to do is to wait for this particular demo to start unless you don't want to play through the game.

There is a topic on nesdev.com about this but for NestopiaUE:
http://forums.nesdev.com/viewtopic.php?f=3&t=13473

There might also be a chance that the ending screen + sound select is glitched to like in NestopiaUE and it's related to this other glitch.

I do own a Famicom and a copy of this game and everything is correct there.

**Comment by SigmaVirus** [comment]
I have been investigating further and the ending + sound select is glitched too:
![punes error 3](https://cloud.githubusercontent.com/assets/14175085/14072954/636ca642-f4c5-11e5-95c6-dcd174982caf.png)

Also this shot here shows what's wrong with the flying shooter stage:
![punes error 2](https://cloud.githubusercontent.com/assets/14175085/14072974/842a68ba-f4c5-11e5-92de-a4485c1f7d50.png)

As you can see the ship is about to fly out in space but the remnants from the ground is still present in the top of the screen.

FHorse I have attached a zip for you containing 3 save states:
1. (.p00) This is the demo from the flying shooter part
2. (.p01) Konami man stands in the hangar ready to take off which means you can control the flying shooter part yourself (press A to get in a ship) and get a sense of what's wrong.
3. (.p02) The game is complete and you can select music etc.

[Wai Wai World (Japan).zip](https://github.com/punesemu/puNES/files/191500/Wai.Wai.World.Japan.zip)

**Comment by lidnariq** [comment]
A recent [hardware](http://forums.nesdev.com/viewtopic.php?p=166985#p166985) test seems to [indicate](http://forums.nesdev.com/viewtopic.php?p=167157#p167157) that prior emulator documentation for the VRC2 was wrong, and that the VRC2 only supports H/V mirroring control. 

It was wrong, of course, because of the historical conflation of the VRC4 and VRC2. But Konami's original VRC2 documentation attests only H/V mirroring.

Normally the VRC2 is upwards-compatible with the VRC4 because all games just write 0 or 1. However, Wai Wai World has a hidden mistake where it writes $FF instead. This value $FF is clearly nonsense: the VRC2 doesn't even connect to the upper 3 data lines. So the hack in FCEUX here is just a way to handle this single instance where a VRC2-using game incorrectly writes with the upper bits set.

**Comment by punesemu** [comment]
[Fixed](https://github.com/punesemu/puNES/commit/889dcb94b759db511dc83f38536ac267f665cc9d)
Thx to Sigma and Lidnariq

**Comment by SigmaVirus** [comment]
You're welcome FHorse!

Any chance of a WIP build to try it out?
