### ISSUE TITLE
Application closes when I start Bandicam.

### ISSUE THREAD

**Issue by griever-gf** [punesemu/puNES#97]
Application closes when I start Bandicam.
If I start Bandicam first, then everything is OK.
puNES version - 0.105
Bandicam version - 3.4.4.1264
OS - Windows 10

**Comment by punesemu** [comment]
Out of curiosity (because I think it's more a Bandicam problem than the emulator) I tried with all versions of puNES on a windows10 but I couldn't reproduce the problem in any way. I started the emulator with bandicam already active and I tried to start bandicam with the emulator already active without problems. Do you have the chance to try on another computer?

**Comment by griever-gf** [comment]
I haven't another PC with Win 10, Win7/8 only.

**Comment by punesemu** [comment]
Another thing, not having bandicam I downloaded the version available on the site (ver. 4.5.0.1587) and I did the tests with that. Perhaps the version you used is too old and maybe the problem had already been solved by the bandicam development team.

**Comment by griever-gf** [comment]
But who closes is puNES, not Bandicam. Why it's Bandicam's problem?
You can find 3.4.4 here: https://rutracker.org/forum/viewtopic.php?t=5289941

**Comment by punesemu** [comment]
Because puNES has nothing to do with bandicam, in fact the emulator works perfectly without bandicam. It's the recording software that attempts to capture the emulator's video screen so it's he who "sticks" to the emulator's output and therefore he performs operations on the emulator executable loaded into the operating system's memory. Have you tried doing a test with the updated version of bandicam? If the crash does not happen with the updated version it's clear that the problem is the old version of bandicam.

**Comment by griever-gf** [comment]
No other software closes because of Bandicam. PuNES only.

**Comment by punesemu** [comment]
Just out of curiosity, could you try the latest [WIP](https://github.com/punesemu/puNES#wip-builds--)?

**Comment by punesemu** [comment]
Closed for inactivity.
